// Mock data with real Ugandan property inspiration
export const mockProperties = [
  {
    id: "1",
    title: "Luxury 4-Bedroom Apartment in Kololo",
    type: "apartment",
    purpose: "sale",
    price: 850000000,
    location: "Kololo, Kampala",
    bedrooms: 4,
    bathrooms: 4,
    status: "active",
    featured: true,
    images: ["/assets/images/image-1.jpg"],
  },
  {
    id: "2",
    title: "Modern Bungalow in Naguru",
    type: "bungalow",
    purpose: "both",
    price: 1200000000,
    location: "Naguru, Kampala",
    bedrooms: 5,
    bathrooms: 5,
    status: "active",
    featured: true,
    images: ["/assets/images/image-2.jpg"],
  },
  {
    id: "3",
    title: "Prime Office Space in Bugolobi",
    type: "office",
    purpose: "rent",
    price: 45000000,
    location: "Bugolobi, Kampala",
    bedrooms: null,
    bathrooms: 6,
    status: "active",
    featured: false,
    images: ["/assets/images/image-3.jpg"]
  },
  
  {
    id: "4",
    title: "Luxury 4-Bedroom Apartment in Kololo",
    type: "apartment",
    purpose: "sale",
    price: 850000000,
    location: "Kololo, Kampala",
    bedrooms: 4,
    bathrooms: 4,
    status: "active",
    featured: true,
    images: ["/assets/images/image-1.jpg"],
  },
  {
    id: "5",
    title: "Modern Bungalow in Naguru",
    type: "bungalow",
    purpose: "both",
    price: 1200000000,
    location: "Naguru, Kampala",
    bedrooms: 5,
    bathrooms: 5,
    status: "active",
    featured: true,
    images: ["/assets/images/image-2.jpg"],
  },
  {
    id: "6",
    title: "Prime Office Space in Bugolobi",
    type: "office",
    purpose: "rent",
    price: 45000000,
    location: "Bugolobi, Kampala",
    bedrooms: null,
    bathrooms: 6,
    status: "active",
    featured: false,
    images: ["/assets/images/image-3.jpg"]
    },
  {
    id: "7",
    title: "Luxury 4-Bedroom Apartment in Kololo",
    type: "apartment",
    purpose: "sale",
    price: 850000000,
    location: "Kololo, Kampala",
    bedrooms: 4,
    bathrooms: 4,
    status: "active",
    featured: true,
    images: ["/assets/images/image-1.jpg"],
  },
  {
    id: "8",
    title: "Modern Bungalow in Naguru",
    type: "bungalow",
    purpose: "both",
    price: 1200000000,
    location: "Naguru, Kampala",
    bedrooms: 5,
    bathrooms: 5,
    status: "active",
    featured: true,
    images: ["/assets/images/image-2.jpg"],
  },
  {
    id: "9",
    title: "Prime Office Space in Bugolobi",
    type: "office",
    purpose: "rent",
    price: 45000000,
    location: "Bugolobi, Kampala",
    bedrooms: null,
    bathrooms: 6,
    status: "active",
    featured: false,
    images: ["/assets/images/image-3.jpg"]
    },
  {
    id: "10",
    title: "Luxury 4-Bedroom Apartment in Kololo",
    type: "apartment",
    purpose: "sale",
    price: 850000000,
    location: "Kololo, Kampala",
    bedrooms: 4,
    bathrooms: 4,
    status: "active",
    featured: true,
    images: ["/assets/images/image-1.jpg"],
  },
  {
    id: "11",
    title: "Modern Bungalow in Naguru",
    type: "bungalow",
    purpose: "both",
    price: 1200000000,
    location: "Naguru, Kampala",
    bedrooms: 5,
    bathrooms: 5,
    status: "active",
    featured: true,
    images: ["/assets/images/image-2.jpg"],
  },
  {
    id: "12",
    title: "Prime Office Space in Bugolobi",
    type: "office",
    purpose: "rent",
    price: 45000000,
    location: "Bugolobi, Kampala",
    bedrooms: null,
    bathrooms: 6,
    status: "active",
    featured: false,
    images: ["/assets/images/image-3.jpg"]
  },
];